### ISSUE TITLE
Crash on old Android version

### ISSUE THREAD

**Issue by Gongreg** [mateusz1913/react-native-avoid-softinput#81]
### Environment

Library version: 2.4.4
OS version: Android 5.0.2, device ZenFone 2 Laser 

### Affected platforms

- [X] Android
- [ ] iOS

### Current behavior

Hello. I've noticed a crash in our crashlytics after including the library in the app.

Stack trace:

```
Fatal Exception: java.lang.NoClassDefFoundError: com.reactnativeavoidsoftinput.AvoidSoftInputManager$mOnScrollListener$1
       at com.reactnativeavoidsoftinput.AvoidSoftInputManager.<init>(AvoidSoftInputManager.kt:71)
       at com.reactnativeavoidsoftinput.AvoidSoftInputModule.<init>(AvoidSoftInputModule.kt:12)
       at com.reactnativeavoidsoftinput.AvoidSoftInputPackage.createNativeModules(AvoidSoftInputPackage.kt:11)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
       at java.lang.Thread.run(Thread.java:818)
```

It happens on a very strange device with an old os version, so I don't know how important it is to look into, but I though it might be useful to report it for you.

### Expected behavior

No crash.

### Reproduction

Usage is very straightforward. We use adjust-nothing in the app and then ```import { useSoftInputHeightChanged } from "react-native-avoid-softinput";    useSoftInputHeightChanged(     useCallback(       ({ softInputHeight }) => { ... },       []     )   )```

**Comment by mateusz1913** [comment]
In the example there was `minSdkVersion` set to 23, that's why it didn't show up earlier, sorry for the inconvenience, version 2.4.6 with the fix is live 🚀 @Gongreg

**Comment by Gongreg** [comment]
Thank you so much for looking into it so fast @mateusz1913 ! 🎉
